// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SQTest

#ifndef _SQTEST_UI_H
#define _SQTEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Recipe
void ui_Recipe_screen_init(void);
extern lv_obj_t * ui_Recipe;
void ui_event_IngredientText(lv_event_t * e);
extern lv_obj_t * ui_IngredientText;
extern lv_obj_t * ui_AvailableIngredientsPanel;
extern lv_obj_t * ui_IngredientsKeyboard;
void ui_event_IngredientsSuggestionPanel(lv_event_t * e);
extern lv_obj_t * ui_IngredientsSuggestionPanel;
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_RecipePanel;
extern lv_obj_t * ui_Label1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_Options
void ui_Options_screen_init(void);
void ui_event_Options(lv_event_t * e);
extern lv_obj_t * ui_Options;
void ui_event_WiFiScan(lv_event_t * e);
extern lv_obj_t * ui_WiFiScan;
extern lv_obj_t * ui_WiFiScanlbl;
extern lv_obj_t * ui_WiFiList;
extern lv_obj_t * ui_WiFiConnectionPnl;
extern lv_obj_t * ui_WiFiPwdKeyboard;
void ui_event_WiFiConnect(lv_event_t * e);
extern lv_obj_t * ui_WiFiConnect;
extern lv_obj_t * ui_WiFiConnectLbl;
void ui_event_WiFiPassword(lv_event_t * e);
extern lv_obj_t * ui_WiFiPassword;
// SCREEN: ui_Components
void ui_Components_screen_init(void);
extern lv_obj_t * ui_Components;
extern lv_obj_t * ui_RecipeItem;
extern lv_obj_t * ui_RecipeImage;
extern lv_obj_t * ui_RecipeLabel;
extern lv_obj_t * ui_ChipPanel;
extern lv_obj_t * ui_CloseLabel;
extern lv_obj_t * ui_ChipText;
extern lv_obj_t * ui_SuggestionButton;
extern lv_obj_t * ui_SuggestionText;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(
    ui_img_3994418_internet_network_signal_wifi_wireless_icon_png);    // assets\3994418_internet_network_signal_wifi_wireless_icon.png
LV_IMG_DECLARE(ui_img_pizza_png);    // assets\pizza.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
