// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SQTest

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void IngredientsTextReady(lv_event_t * e);
void IngredientsTextValueChanged(lv_event_t * e);
void Button_Clicked_1(lv_event_t * e);
void ScanWifi_Clicked(lv_event_t * e);
void WiFiConnect_Clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
