// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SQTest

#include "../ui.h"


void ui_event_comp_PanelRecipe_RecipeSelectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_PanelRecipe = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        RecipeSelectClicked(e);
    }
}

// COMPONENT PanelRecipe

lv_obj_t * ui_PanelRecipe_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_PanelRecipe;
    cui_PanelRecipe = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_PanelRecipe, 251);
    lv_obj_set_height(cui_PanelRecipe, 402);
    lv_obj_set_x(cui_PanelRecipe, -266);
    lv_obj_set_y(cui_PanelRecipe, 29);
    lv_obj_set_align(cui_PanelRecipe, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_PanelRecipe, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_PanelRecipe, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_PanelRecipe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(cui_PanelRecipe, lv_color_hex(0x989898), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_PanelRecipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_PanelRecipe, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_PanelRecipe, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_PanelRecipe, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_PanelRecipe, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_RecipeTitle0;
    cui_RecipeTitle0 = lv_label_create(cui_PanelRecipe);
    lv_obj_set_height(cui_RecipeTitle0, 69);
    lv_obj_set_width(cui_RecipeTitle0, lv_pct(100));
    lv_obj_set_align(cui_RecipeTitle0, LV_ALIGN_CENTER);
    lv_label_set_text(cui_RecipeTitle0, "");
    lv_obj_set_style_text_color(cui_RecipeTitle0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_RecipeTitle0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_RecipeTitle0, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_RecipeTitle0, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_RecipeTitle0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_RecipeTitle0, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_RecipeTitle0, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_RecipeTitle0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_RecipeTitle0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_PanelIngredients;
    cui_PanelIngredients = lv_obj_create(cui_PanelRecipe);
    lv_obj_set_width(cui_PanelIngredients, lv_pct(100));
    lv_obj_set_height(cui_PanelIngredients, lv_pct(65));
    lv_obj_set_align(cui_PanelIngredients, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_PanelIngredients, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_PanelIngredients, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_border_width(cui_PanelIngredients, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_PanelIngredients, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_PanelIngredients, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_PanelIngredients, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_PanelIngredients, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_RecipeIngredients0;
    cui_RecipeIngredients0 = lv_label_create(cui_PanelIngredients);
    lv_obj_set_width(cui_RecipeIngredients0, lv_pct(100));
    lv_obj_set_height(cui_RecipeIngredients0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_RecipeIngredients0, LV_ALIGN_CENTER);
    lv_label_set_text(cui_RecipeIngredients0, "");

    lv_obj_t * cui_PanelIngredientsButton;
    cui_PanelIngredientsButton = lv_obj_create(cui_PanelRecipe);
    lv_obj_set_width(cui_PanelIngredientsButton, lv_pct(100));
    lv_obj_set_height(cui_PanelIngredientsButton, lv_pct(12));
    lv_obj_set_align(cui_PanelIngredientsButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_PanelIngredientsButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_PanelIngredientsButton, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_border_width(cui_PanelIngredientsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_PanelIngredientsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_PanelIngredientsButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_PanelIngredientsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_PanelIngredientsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_RecipeSelectBtn;
    cui_RecipeSelectBtn = lv_btn_create(cui_PanelIngredientsButton);
    lv_obj_set_width(cui_RecipeSelectBtn, 100);
    lv_obj_set_height(cui_RecipeSelectBtn, 42);
    lv_obj_set_align(cui_RecipeSelectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_RecipeSelectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_RecipeSelectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_SelectLbl;
    cui_SelectLbl = lv_label_create(cui_RecipeSelectBtn);
    lv_obj_set_width(cui_SelectLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_SelectLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_SelectLbl, LV_ALIGN_CENTER);
    lv_label_set_long_mode(cui_SelectLbl, LV_LABEL_LONG_CLIP);
    lv_label_set_text(cui_SelectLbl, "Select");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANELRECIPE_NUM);
    children[UI_COMP_PANELRECIPE_PANELRECIPE] = cui_PanelRecipe;
    children[UI_COMP_PANELRECIPE_RECIPETITLE0] = cui_RecipeTitle0;
    children[UI_COMP_PANELRECIPE_PANELINGREDIENTS] = cui_PanelIngredients;
    children[UI_COMP_PANELRECIPE_PANELINGREDIENTS_RECIPEINGREDIENTS0] = cui_RecipeIngredients0;
    children[UI_COMP_PANELRECIPE_PANELINGREDIENTSBUTTON] = cui_PanelIngredientsButton;
    children[UI_COMP_PANELRECIPE_PANELINGREDIENTSBUTTON_RECIPESELECTBTN] = cui_RecipeSelectBtn;
    children[UI_COMP_PANELRECIPE_PANELINGREDIENTSBUTTON_RECIPESELECTBTN_SELECTLBL] = cui_SelectLbl;
    lv_obj_add_event_cb(cui_PanelRecipe, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_PanelRecipe, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_RecipeSelectBtn, ui_event_comp_PanelRecipe_RecipeSelectBtn, LV_EVENT_ALL, children);
    ui_comp_PanelRecipe_create_hook(cui_PanelRecipe);
    return cui_PanelRecipe;
}

