// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SQTest

#ifndef _UI_COMP_PANELRECIPE_H
#define _UI_COMP_PANELRECIPE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PanelRecipe
#define UI_COMP_PANELRECIPE_PANELRECIPE 0
#define UI_COMP_PANELRECIPE_RECIPETITLE0 1
#define UI_COMP_PANELRECIPE_PANELINGREDIENTS 2
#define UI_COMP_PANELRECIPE_PANELINGREDIENTS_RECIPEINGREDIENTS0 3
#define UI_COMP_PANELRECIPE_PANELINGREDIENTSBUTTON 4
#define UI_COMP_PANELRECIPE_PANELINGREDIENTSBUTTON_RECIPESELECTBTN 5
#define UI_COMP_PANELRECIPE_PANELINGREDIENTSBUTTON_RECIPESELECTBTN_SELECTLBL 6
#define _UI_COMP_PANELRECIPE_NUM 7
lv_obj_t * ui_PanelRecipe_create(lv_obj_t * comp_parent);
void ui_event_comp_PanelRecipe_RecipeSelectBtn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
