// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SQTest

#include "../ui.h"

void ui_Components_screen_init(void)
{
    ui_Components = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Components, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RecipeItem = lv_obj_create(ui_Components);
    lv_obj_remove_style_all(ui_RecipeItem);
    lv_obj_set_width(ui_RecipeItem, 358);
    lv_obj_set_height(ui_RecipeItem, 70);
    lv_obj_set_x(ui_RecipeItem, -195);
    lv_obj_set_y(ui_RecipeItem, -185);
    lv_obj_set_align(ui_RecipeItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RecipeItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RecipeItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RecipeItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RecipeImage = lv_img_create(ui_RecipeItem);
    lv_obj_set_width(ui_RecipeImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecipeImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RecipeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RecipeImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RecipeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RecipeLabel = lv_label_create(ui_RecipeItem);
    lv_obj_set_width(ui_RecipeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecipeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RecipeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecipeLabel, "Recipe");

    ui_ChipPanel = lv_obj_create(ui_Components);
    lv_obj_set_width(ui_ChipPanel, 100);
    lv_obj_set_height(ui_ChipPanel, 35);
    lv_obj_set_x(ui_ChipPanel, -223);
    lv_obj_set_y(ui_ChipPanel, -14);
    lv_obj_set_align(ui_ChipPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ChipPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ChipPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ChipPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ChipPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChipPanel, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChipPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChipPanel, lv_color_hex(0x848484), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChipPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChipPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CloseLabel = lv_label_create(ui_ChipPanel);
    lv_obj_set_width(ui_CloseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CloseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CloseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CloseLabel, "x");

    ui_ChipText = lv_label_create(ui_ChipPanel);
    lv_obj_set_width(ui_ChipText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChipText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChipText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChipText, "dsf ");

    ui_SuggestionButton = lv_btn_create(ui_Components);
    lv_obj_set_width(ui_SuggestionButton, 168);
    lv_obj_set_height(ui_SuggestionButton, 30);
    lv_obj_set_x(ui_SuggestionButton, -177);
    lv_obj_set_y(ui_SuggestionButton, 64);
    lv_obj_set_align(ui_SuggestionButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SuggestionButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SuggestionButton, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_SuggestionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SuggestionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SuggestionButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SuggestionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SuggestionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SuggestionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SuggestionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SuggestionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SuggestionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SuggestionButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SuggestionText = lv_label_create(ui_SuggestionButton);
    lv_obj_set_width(ui_SuggestionText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SuggestionText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SuggestionText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SuggestionText, "aaaa");
    lv_obj_set_style_text_color(ui_SuggestionText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SuggestionText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
