// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SQTest

#include "../ui.h"

void ui_Recipe_screen_init(void)
{
    ui_Recipe = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Recipe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IngredientText = lv_textarea_create(ui_Recipe);
    lv_obj_set_width(ui_IngredientText, 770);
    lv_obj_set_height(ui_IngredientText, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_IngredientText, 1);
    lv_obj_set_y(ui_IngredientText, -188);
    lv_obj_set_align(ui_IngredientText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_IngredientText, "Ingredient...");
    lv_textarea_set_one_line(ui_IngredientText, true);



    ui_AvailableIngredientsPanel = lv_obj_create(ui_Recipe);
    lv_obj_set_width(ui_AvailableIngredientsPanel, 764);
    lv_obj_set_height(ui_AvailableIngredientsPanel, 63);
    lv_obj_set_x(ui_AvailableIngredientsPanel, -1);
    lv_obj_set_y(ui_AvailableIngredientsPanel, -127);
    lv_obj_set_align(ui_AvailableIngredientsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AvailableIngredientsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AvailableIngredientsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_IngredientsKeyboard = lv_keyboard_create(ui_Recipe);
    lv_obj_set_width(ui_IngredientsKeyboard, 499);
    lv_obj_set_height(ui_IngredientsKeyboard, 264);
    lv_obj_set_x(ui_IngredientsKeyboard, 118);
    lv_obj_set_y(ui_IngredientsKeyboard, 52);
    lv_obj_set_align(ui_IngredientsKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IngredientsKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_IngredientsSuggestionPanel = lv_obj_create(ui_Recipe);
    lv_obj_set_width(ui_IngredientsSuggestionPanel, 235);
    lv_obj_set_height(ui_IngredientsSuggestionPanel, 209);
    lv_obj_set_x(ui_IngredientsSuggestionPanel, -267);
    lv_obj_set_y(ui_IngredientsSuggestionPanel, -59);
    lv_obj_set_align(ui_IngredientsSuggestionPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IngredientsSuggestionPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_IngredientsSuggestionPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_IngredientsSuggestionPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_IngredientText, ui_event_IngredientText, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_IngredientsKeyboard, ui_IngredientText);
    lv_obj_add_event_cb(ui_IngredientsSuggestionPanel, ui_event_IngredientsSuggestionPanel, LV_EVENT_ALL, NULL);

}
