// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SQTest

#include "../ui.h"

void ui_Recipe_screen_init(void)
{
    ui_Recipe = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Recipe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Recipe, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GetRecipeButton = lv_btn_create(ui_Recipe);
    lv_obj_set_width(ui_GetRecipeButton, 135);
    lv_obj_set_height(ui_GetRecipeButton, 50);
    lv_obj_set_x(ui_GetRecipeButton, 311);
    lv_obj_set_y(ui_GetRecipeButton, 192);
    lv_obj_set_align(ui_GetRecipeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GetRecipeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GetRecipeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GetRecipesLbl = lv_label_create(ui_GetRecipeButton);
    lv_obj_set_width(ui_GetRecipesLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GetRecipesLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GetRecipesLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GetRecipesLbl, "Get Recipes");

    ui_TopPanel = lv_obj_create(ui_Recipe);
    lv_obj_set_width(ui_TopPanel, 803);
    lv_obj_set_height(ui_TopPanel, 168);
    lv_obj_set_x(ui_TopPanel, 0);
    lv_obj_set_y(ui_TopPanel, -157);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TopPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_Image3, &ui_img_9921876_spoon_fork_kitchen_restaurant_utensil_icon_png);
    lv_obj_set_width(ui_Image3, 55);
    lv_obj_set_height(ui_Image3, 59);
    lv_obj_set_x(ui_Image3, -346);
    lv_obj_set_y(ui_Image3, 37);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AvailableIngredientsPanel = lv_obj_create(ui_TopPanel);
    lv_obj_set_width(ui_AvailableIngredientsPanel, 682);
    lv_obj_set_height(ui_AvailableIngredientsPanel, 73);
    lv_obj_set_x(ui_AvailableIngredientsPanel, 39);
    lv_obj_set_y(ui_AvailableIngredientsPanel, 36);
    lv_obj_set_align(ui_AvailableIngredientsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AvailableIngredientsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AvailableIngredientsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_AvailableIngredientsPanel, LV_DIR_HOR);
    lv_obj_set_style_border_color(ui_AvailableIngredientsPanel, lv_color_hex(0x989898), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AvailableIngredientsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IngredientText = lv_textarea_create(ui_TopPanel);
    lv_obj_set_width(ui_IngredientText, 747);
    lv_obj_set_height(ui_IngredientText, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_IngredientText, 6);
    lv_obj_set_y(ui_IngredientText, -32);
    lv_obj_set_align(ui_IngredientText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_IngredientText, "Ingredients...");
    lv_textarea_set_one_line(ui_IngredientText, true);
    lv_obj_set_style_radius(ui_IngredientText, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IngredientText, lv_color_hex(0x989898), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IngredientText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label2 = lv_label_create(ui_Recipe);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -361);
    lv_obj_set_y(ui_Label2, -53);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Meal");

    ui_Container1 = lv_obj_create(ui_Recipe);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 45);
    lv_obj_set_width(ui_Container1, lv_pct(98));
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -12);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BreakfastBtn = lv_btn_create(ui_Container1);
    lv_obj_set_height(ui_BreakfastBtn, 40);
    lv_obj_set_width(ui_BreakfastBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BreakfastBtn, -307);
    lv_obj_set_y(ui_BreakfastBtn, -10);
    lv_obj_set_align(ui_BreakfastBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BreakfastBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BreakfastBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BreakfastBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MealButtonText = lv_label_create(ui_BreakfastBtn);
    lv_obj_set_width(ui_MealButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MealButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MealButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MealButtonText, "BREAKFAST");

    ui_LunchBtn = lv_btn_create(ui_Container1);
    lv_obj_set_height(ui_LunchBtn, 40);
    lv_obj_set_width(ui_LunchBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_LunchBtn, -141);
    lv_obj_set_y(ui_LunchBtn, -11);
    lv_obj_set_align(ui_LunchBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LunchBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LunchBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LunchBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_LunchBtn);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "LUNCH");

    ui_SoupBtn = lv_btn_create(ui_Container1);
    lv_obj_set_height(ui_SoupBtn, 40);
    lv_obj_set_width(ui_SoupBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_SoupBtn, -141);
    lv_obj_set_y(ui_SoupBtn, -11);
    lv_obj_set_align(ui_SoupBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SoupBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SoupBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SoupBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_SoupBtn);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SOUP");

    ui_DinnerBtn = lv_btn_create(ui_Container1);
    lv_obj_set_height(ui_DinnerBtn, 40);
    lv_obj_set_width(ui_DinnerBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_DinnerBtn, -141);
    lv_obj_set_y(ui_DinnerBtn, -11);
    lv_obj_set_align(ui_DinnerBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DinnerBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DinnerBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DinnerBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_DinnerBtn);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "DINNER");

    ui_Label7 = lv_label_create(ui_Recipe);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -350);
    lv_obj_set_y(ui_Label7, 31);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Cuisine");

    ui_Container2 = lv_obj_create(ui_Recipe);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 45);
    lv_obj_set_width(ui_Container2, lv_pct(98));
    lv_obj_set_x(ui_Container2, -1);
    lv_obj_set_y(ui_Container2, 77);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ItalianBtn = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_ItalianBtn, 40);
    lv_obj_set_width(ui_ItalianBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_ItalianBtn, -307);
    lv_obj_set_y(ui_ItalianBtn, -10);
    lv_obj_set_align(ui_ItalianBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ItalianBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ItalianBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ItalianBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ItalianBtn, lv_color_hex(0x005D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ItalianBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_ItalianBtn);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "ITALIAN");

    ui_ThaiBtn = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_ThaiBtn, 40);
    lv_obj_set_width(ui_ThaiBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_ThaiBtn, -141);
    lv_obj_set_y(ui_ThaiBtn, -11);
    lv_obj_set_align(ui_ThaiBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThaiBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ThaiBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ThaiBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThaiBtn, lv_color_hex(0x005D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThaiBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_ThaiBtn);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "THAI");

    ui_MexBtn = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_MexBtn, 40);
    lv_obj_set_width(ui_MexBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_MexBtn, -141);
    lv_obj_set_y(ui_MexBtn, -11);
    lv_obj_set_align(ui_MexBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MexBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MexBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MexBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MexBtn, lv_color_hex(0x005D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MexBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_MexBtn);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "MEX");

    ui_IndianBtn = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_IndianBtn, 40);
    lv_obj_set_width(ui_IndianBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_IndianBtn, -141);
    lv_obj_set_y(ui_IndianBtn, -11);
    lv_obj_set_align(ui_IndianBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IndianBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IndianBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IndianBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IndianBtn, lv_color_hex(0x005D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IndianBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_IndianBtn);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "INDIAN");

    ui_ChineseBtn = lv_btn_create(ui_Container2);
    lv_obj_set_height(ui_ChineseBtn, 40);
    lv_obj_set_width(ui_ChineseBtn, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_ChineseBtn, -141);
    lv_obj_set_y(ui_ChineseBtn, -11);
    lv_obj_set_align(ui_ChineseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChineseBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ChineseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ChineseBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChineseBtn, lv_color_hex(0x005D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChineseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_ChineseBtn);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "CHINESE");

    ui_IngredientsSuggestionPanel = lv_obj_create(ui_Recipe);
    lv_obj_set_width(ui_IngredientsSuggestionPanel, 235);
    lv_obj_set_height(ui_IngredientsSuggestionPanel, 149);
    lv_obj_set_x(ui_IngredientsSuggestionPanel, -246);
    lv_obj_set_y(ui_IngredientsSuggestionPanel, -86);
    lv_obj_set_align(ui_IngredientsSuggestionPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IngredientsSuggestionPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_IngredientsSuggestionPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_IngredientsSuggestionPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_IngredientsKeyboard = lv_keyboard_create(ui_Recipe);
    lv_obj_set_width(ui_IngredientsKeyboard, 788);
    lv_obj_set_height(ui_IngredientsKeyboard, 264);
    lv_obj_set_x(ui_IngredientsKeyboard, -3);
    lv_obj_set_y(ui_IngredientsKeyboard, 103);
    lv_obj_set_align(ui_IngredientsKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IngredientsKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_GetRecipeButton, ui_event_GetRecipeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IngredientText, ui_event_IngredientText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IngredientsSuggestionPanel, ui_event_IngredientsSuggestionPanel, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_IngredientsKeyboard, ui_IngredientText);

}
