// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SQTest

#include "../ui.h"

void ui_StepByStep_screen_init(void)
{
    ui_StepByStep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StepByStep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitlePnl = lv_obj_create(ui_StepByStep);
    lv_obj_set_height(ui_TitlePnl, 50);
    lv_obj_set_width(ui_TitlePnl, lv_pct(98));
    lv_obj_set_x(ui_TitlePnl, 1);
    lv_obj_set_y(ui_TitlePnl, -179);
    lv_obj_set_align(ui_TitlePnl, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TitlePnl, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TitlePnl, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TitlePnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RecipeTitleLbl = lv_label_create(ui_TitlePnl);
    lv_obj_set_width(ui_RecipeTitleLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecipeTitleLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RecipeTitleLbl, LV_ALIGN_CENTER);
    lv_obj_set_style_text_decor(ui_RecipeTitleLbl, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecipeTitleLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitlePnl1 = lv_obj_create(ui_StepByStep);
    lv_obj_set_height(ui_TitlePnl1, 308);
    lv_obj_set_width(ui_TitlePnl1, lv_pct(98));
    lv_obj_set_x(ui_TitlePnl1, 1);
    lv_obj_set_y(ui_TitlePnl1, 7);
    lv_obj_set_align(ui_TitlePnl1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TitlePnl1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TitlePnl1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TitlePnl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RecipeStepLbl = lv_label_create(ui_TitlePnl1);
    lv_obj_set_width(ui_RecipeStepLbl, lv_pct(100));
    lv_obj_set_height(ui_RecipeStepLbl, lv_pct(100));
    lv_obj_set_align(ui_RecipeStepLbl, LV_ALIGN_CENTER);
    lv_obj_set_style_text_decor(ui_RecipeStepLbl, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecipeStepLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextStepBtn = lv_btn_create(ui_StepByStep);
    lv_obj_set_width(ui_NextStepBtn, 135);
    lv_obj_set_height(ui_NextStepBtn, 50);
    lv_obj_set_x(ui_NextStepBtn, 321);
    lv_obj_set_y(ui_NextStepBtn, 202);
    lv_obj_set_align(ui_NextStepBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NextStepBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextStepBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextLbl = lv_label_create(ui_NextStepBtn);
    lv_obj_set_width(ui_NextLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NextLbl, "NEXT");

    ui_PrevStepBtn = lv_btn_create(ui_StepByStep);
    lv_obj_set_width(ui_PrevStepBtn, 135);
    lv_obj_set_height(ui_PrevStepBtn, 50);
    lv_obj_set_x(ui_PrevStepBtn, -321);
    lv_obj_set_y(ui_PrevStepBtn, 206);
    lv_obj_set_align(ui_PrevStepBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrevStepBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrevStepBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrevLbl = lv_label_create(ui_PrevStepBtn);
    lv_obj_set_width(ui_PrevLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrevLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrevLbl, 1);
    lv_obj_set_y(ui_PrevLbl, 0);
    lv_obj_set_align(ui_PrevLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrevLbl, "PREVIOUS");

    lv_obj_add_event_cb(ui_NextStepBtn, ui_event_NextStepBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrevStepBtn, ui_event_PrevStepBtn, LV_EVENT_ALL, NULL);

}
